#include <iostream>
#include <cstdlib>
#include <ctime>
#include <stdlib.h>
using namespace std;
void won(){
   cout<<endl;
    cout << "W       W   OOO   N   N" << endl;
    cout << " W     W   O   O  NN  N" << endl;
    cout << "  W W W   O   O  N N N" << endl;
    cout << "   W W    O   O  N  NN" << endl;
    cout << "   W W     OOO   N   N" << endl; 
}
void lost(){
     cout << "  L      OOO   SSS  TTTTT" << endl;
    cout << "  L     O   O  S       T  " << endl;
    cout << "  L     O   O   SS     T  " << endl;
    cout << "  L     O   O     S    T  " << endl;
    cout << "  LLLL   OOO   SSS     T  " << endl;
}
void play(){
     cout << "  L      EEEEE  TTTTT  '    SSSS         PPPP   L        A     Y   Y  !!" << endl;
    cout << "  L      E        T          S            P   P  L       A A     Y Y   !!" << endl;
    cout << "  L      EEEE     T          SSSS         PPPP   L      AAAAA     Y    !!" << endl;
    cout << "  L      E        T             S         P      L     A     A    Y    !!" << endl;
    cout << "  LLLL   EEEEE    T          SSSS         P      LLLL A       A   Y    !!" << endl;
}
//menu driven funtion
int menu()
{ play();
    cout << "Let's Play:->" << endl;
    cout<<"\nEnter the difficulty level:";
    cout<<"\n1.Easy\n2.Medium\n3.Hard\n4.Exit";
    cout << "\nEnter your choice:";
    int x;
    cin >> x;
    return x;
}
//game logic
void game(int n)
{
    srand((unsigned int)time(NULL));
    // random function generated the number which we have to guess
    int number = rand() % 100 + 1;
    // initialize guess variable where user will guess the no. generated by random function
    int guess = 0, i;
    for (i = 1; i <= n; i++)
    {

        cout << "\nGuess (1-100)->"; // guess a number b\w 1 to 100
        cin >> guess;
        if (guess > number)
            cout << "\nGuess Lower!"; // user had guessed higher so guess lower
        else if (guess < number)
            cout << "\n Guess Higher!"; // user had guessed lower so guess higher
        else
        {
            cout << "\nCongratulation! You won!"; // user had  guessed correctly
            won();
            return;
        }
        cout << "\nRemaining changes are " << n - i << endl;
    }
    cout << "\nYou Lost! Game Over! Play Again!\n";
    lost();
}
//driver code
int main()
{
    //inifite loop
    while (1)
    {
            cout<<endl;
            cout<<endl;
            cout<<endl;
        //switch case
        switch (menu())
        {
        case 1:
            game(10);//get 10 chances to play for easy
            break;
        case 2:
            game(7);//get 7 chances to play for medium
            break;
        case 3:
            game(5);//get 5 chances to play for hard
            break;
        case 4:
            exit(1);

        default:
            cout << "\nInvalid Input!";
        }
    }
    return 0;
}